// test/golden/margin-references.test.ts
//
// Phase 3 Task 7 — reference-quality checks for the dentist's hand-traced
// margin fixtures (test-fixtures/margins/arch-case-01/<tooth>.reference.json
// — FDI 12, 11, 21, 22 — produced by engine/marginEditor.ts's dev-only
// `exportReferenceMargin()`; see that directory's README.md for the full
// schema/workflow doc). This task LANDS THE TOOLING before the human
// tracing session happens — the controller schedules that session
// separately (docs/plans/phase-3-margin-axis.md Task 7's brief, deliverable
// 2, "Controller/user step (NOT a subagent step)"). Every check below
// therefore SKIPS (not fails) a tooth whose reference file isn't committed
// yet, with an explicit message naming the missing path, so `npm run
// test:golden` stays green in BOTH states — before this task's tooling
// lands, immediately after, and once the four files eventually arrive.
//
// ## "Golden integrity" without a checksums.json (deliberate — see
// test-fixtures/margins/README.md's own "Golden integrity" section for the
// full reasoning, summarized here)
//
// Every other golden-* fixture in this repo is machine-regenerated by a
// script; pinning ITS hash catches "the live kernel produced something
// different than last time." These references are hand-traced — there is
// no regenerate step, so a standalone sha256 pin would only ever assert
// "this file hasn't silently changed since the check was written," which
// is EXACTLY what scripts/check-golden-version-gate.ts's
// `GOLDEN_PATH_PATTERNS` (extended by this same task to cover
// `test-fixtures/margins/**/*.reference.json`) already enforces for the
// whole repo: any PR touching a committed reference file must bump
// KERNEL_VERSION + add a changelog entry, or CI's version-gate job fails.
// A separate checksums.json would duplicate that mechanism (and could
// silently drift from it) for no additional coverage — so this file
// computes/asserts nothing hash-wise on its own; it only checks structural/
// geometric validity, every run, against whatever is currently committed.
import { existsSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  buildBvh,
  validateMarginLine,
  classifyMarginValidation,
  type IndexedMesh,
  type MarginLineLike,
} from '@dqcad/kernel';
import type { MarginReferenceExport } from '@dqcad/shared-types';
import { repoRoot } from '../../scripts/kernel-ops-lib.ts';
import { loadUpperjawMesh } from './upperjaw-mesh.ts';

const MARGINS_DIR = 'test-fixtures/margins/arch-case-01';
const REFERENCE_TEETH = [12, 11, 21, 22] as const;

/** The allow-listed field set `MarginReferenceExport` (packages/shared-types)
 * declares — this IS the no-PHI check: any extra/unexpected key on a
 * committed reference file fails here, not just a manual review. Sorted so
 * the comparison below is order-independent. */
const EXPECTED_KEYS = [
  'tooth',
  'anchors',
  'closed',
  'resampledPoints',
  'meshContentHash',
  'traced',
  'appVersion',
  'kernelVersion',
  'exportedAt',
].sort();

// ---------------------------------------------------------------------------
// Real upperjaw mesh — loaded + intake'd (welded, post-processing) at most
// once, lazily, only if at least one reference file actually needs it
// (memoized module-level singleton — same "load the real LFS fixture only
// when actually exercised" spirit as margin-validate.test.ts's own
// loadUpperjawMesh, just cached here since THIS file may re-load it across
// up to 4 independent teeth).
// ---------------------------------------------------------------------------
let cachedMesh: IndexedMesh | null = null;
function loadUpperjawMeshOnce(): IndexedMesh {
  if (cachedMesh) return cachedMesh;
  cachedMesh = loadUpperjawMesh();
  return cachedMesh;
}

/** SHA-256(positions-bytes, indices-bytes) — the SAME byte-layout
 * convention `@dqcad/kernel-workers`' hash.ts's `hashMeshContent` uses
 * (positions Float64 bytes, then indices Uint32 bytes, lowercase hex),
 * reimplemented locally rather than reaching into kernel-workers' internal
 * module — the established convention this repo's OTHER golden tests
 * already follow (see scripts/kernel-ops-lib.ts's own `sha256Of`/
 * `hashMesh`, whose module doc explicitly notes "used throughout this
 * repo's golden tests ... all reimplement this independently"). Producing
 * the SAME hash a real app import of this exact STL would assign as the
 * mesh's `MeshAsset.contentHash` (CLAUDE.md determinism invariant: same
 * inputs + kernel version -> bit-identical outputs) is what makes this a
 * meaningful "does this reference still point at the right mesh" check. */
function hashMeshContentHex(mesh: IndexedMesh): string {
  const hash = createHash('sha256');
  hash.update(Buffer.from(mesh.positions.buffer, mesh.positions.byteOffset, mesh.positions.byteLength));
  hash.update(Buffer.from(mesh.indices.buffer, mesh.indices.byteOffset, mesh.indices.byteLength));
  return hash.digest('hex');
}

type Vec3 = readonly [number, number, number];

/** Consecutive-point spacings (mm) along `points`, wrapping around iff
 * `closed` — the same "segments[i] joins points[i] -> points[(i+1) % n]"
 * convention this repo's live editor uses (apps/client/src/state/
 * marginStore.ts's `LiveMarginSegment` doc). */
function polylineSpacingsMm(points: readonly Vec3[], closed: boolean): number[] {
  const n = points.length;
  const segCount = closed ? n : Math.max(0, n - 1);
  const spacings: number[] = [];
  for (let i = 0; i < segCount; i++) {
    const a = points[i]!;
    const b = points[(i + 1) % n]!;
    spacings.push(Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]));
  }
  return spacings;
}

// ---------------------------------------------------------------------------
// Density sanity band (NOT a clinical or algorithmic spec — see this file's
// module doc and test-fixtures/margins/README.md's "Density" section).
// `resampledPoints` is the concatenation of real geodesic shortest paths
// between anchors (one point per triangle-edge crossing along the walk),
// so its density tracks LOCAL MESH RESOLUTION, not a fixed arc-length step.
// arch-case-01's upperjaw manifest (test-fixtures/real-scans/arch-case-01/
// manifest.json) records ~250k triangles over a ~68mm x 50mm arch bbox —
// consistent with a typical intraoral-scanner triangle edge on the order of
// 100-200 µm. The bounds below give generous headroom around that estimate:
// a MEAN spacing outside [5 µm, 1 mm] would mean either near-duplicate
// points (below the floor) or an implausibly coarse polyline for a
// margin-scale curve (above the ceiling); a single gap above 5 mm — a
// meaningful fraction of a ~20-30mm closed loop — would mean a badly
// under-resolved segment, not normal mesh-resolution variation.
// ---------------------------------------------------------------------------
const MEAN_SPACING_MIN_MM = 0.005;
const MEAN_SPACING_MAX_MM = 1.0;
const MAX_SINGLE_GAP_MM = 5.0;

// Loose anatomical sanity for an upper incisor/canine finish-line
// circumference — NOT clinical dogma (per this task's brief, and
// test-fixtures/margins/README.md's own "loose anatomical sanity" framing).
// Wide enough to admit real anatomical variation and margin-design choice
// (supragingival vs. subgingival, chamfer vs. shoulder extent) while still
// catching a badly wrong trace (e.g. an accidentally-huge or
// near-degenerate loop).
// 15-35 mm per the phase plan (docs/plans/phase-3-margin-axis.md §Task 7) —
// the plan's number governs (an earlier 12-40 draft came from a dispatch
// prompt, not the plan; adjudicated by the controller 2026-07-15).
const CIRCUMFERENCE_MIN_MM = 15;
const CIRCUMFERENCE_MAX_MM = 35;

function referencePath(tooth: number): string {
  return join(repoRoot, MARGINS_DIR, `${tooth}.reference.json`);
}

describe('margin references — arch-case-01 (Phase 3 Task 7)', () => {
  for (const tooth of REFERENCE_TEETH) {
    const path = referencePath(tooth);
    const relPath = `${MARGINS_DIR}/${tooth}.reference.json`;

    if (!existsSync(path)) {
      // SKIP gracefully, with an explicit message — the human tracing
      // session (Task 7's deliverable 2) hasn't landed this tooth yet.
      // `it.skip` (not a thrown error / test.fails) keeps `npm run
      // test:golden` green either way, per this file's module doc.
      it.skip(`tooth ${tooth}: SKIPPED — ${relPath} not committed yet (human tracing session pending)`, () => {});
      continue;
    }

    describe(`tooth ${tooth} (${relPath})`, () => {
      const raw = readFileSync(path, 'utf8');
      const parsed = JSON.parse(raw) as MarginReferenceExport;

      it('matches the reference JSON schema — allow-listed keys only (no-PHI check)', () => {
        expect(Object.keys(parsed).sort()).toEqual(EXPECTED_KEYS);
        expect(parsed.tooth).toBe(tooth);
        expect(parsed.traced).toBe('human-reference');
        expect(typeof parsed.meshContentHash).toBe('string');
        expect(parsed.meshContentHash.length).toBe(64); // hex SHA-256
        expect(typeof parsed.appVersion).toBe('string');
        expect(typeof parsed.kernelVersion).toBe('string');
        expect(() => new Date(parsed.exportedAt).toISOString()).not.toThrow();
      });

      it('CRITICAL: passes Task 6 validation against the real upperjaw mesh — closed, non-self-intersecting, on-surface, non-degenerate', () => {
        const mesh = loadUpperjawMeshOnce();
        const bvh = buildBvh(mesh);
        const margin: MarginLineLike = {
          anchors: parsed.anchors,
          closed: parsed.closed,
          resampledPoints: parsed.resampledPoints,
        };
        const report = validateMarginLine(mesh, bvh, margin);
        const classification = classifyMarginValidation(report);

        expect(parsed.closed).toBe(true); // Task 6 gate: 'open' blocks confirm — a reference can never be open.
        expect(report.closed).toBe(true);
        expect(report.selfIntersecting).toBe(false);
        expect(report.onSurface).toBe(true);
        expect(report.degenerate).toBe(false);
        expect(classification.blocked).toBe(false);
        expect(classification.hardFailureKinds).toEqual([]);
        if (classification.hasWarnings) {
          // Smoothness is a WARNING, not a hard failure (Task 6's gate
          // semantics) — a human trace that required "acknowledge and
          // confirm" is still a legitimate, committed reference. Logged
          // (not failed) for visibility.
          console.log(
            `[margin-references] tooth ${tooth}: ${report.smoothnessWarnings.length} smoothness warning(s) present (acknowledged at confirm time, per Task 6's gate).`,
          );
        }
      });

      it('resampledPoints density is within the standard sanity band', () => {
        expect(parsed.resampledPoints.length).toBeGreaterThanOrEqual(3);
        const spacings = polylineSpacingsMm(parsed.resampledPoints, parsed.closed);
        expect(spacings.length).toBeGreaterThan(0);
        const mean = spacings.reduce((sum, v) => sum + v, 0) / spacings.length;
        const max = Math.max(...spacings);
        console.log(
          `[margin-references] tooth ${tooth}: resampledPoints=${parsed.resampledPoints.length}, meanSpacingMm=${mean.toFixed(4)}, maxSpacingMm=${max.toFixed(4)}`,
        );
        expect(mean).toBeGreaterThanOrEqual(MEAN_SPACING_MIN_MM);
        expect(mean).toBeLessThanOrEqual(MEAN_SPACING_MAX_MM);
        expect(max).toBeLessThanOrEqual(MAX_SINGLE_GAP_MM);
      });

      it('circumference is within loose anatomical sanity bounds (15-35mm for an upper incisor/canine — sanity, not clinical dogma)', () => {
        const spacings = polylineSpacingsMm(parsed.resampledPoints, parsed.closed);
        const circumferenceMm = spacings.reduce((sum, v) => sum + v, 0);
        console.log(`[margin-references] tooth ${tooth}: circumferenceMm=${circumferenceMm.toFixed(3)}`);
        expect(circumferenceMm).toBeGreaterThanOrEqual(CIRCUMFERENCE_MIN_MM);
        expect(circumferenceMm).toBeLessThanOrEqual(CIRCUMFERENCE_MAX_MM);
      });

      it('meshContentHash matches the actual, freshly-computed content hash of the arch-case-01 upperjaw fixture mesh', () => {
        const mesh = loadUpperjawMeshOnce();
        const expectedHash = hashMeshContentHex(mesh);
        // If this ever fails for ALL references at once after a tracing
        // session, check first whether the in-app import applied a
        // unit-rescale (importer.ts's pre-intake rescale branch) — this test
        // replicates parse+intake but NOT rescale-on-import. arch-case-01 is
        // well within mm-scale so it can't trigger today; a future
        // differently-scaled fixture could.
        expect(parsed.meshContentHash).toBe(expectedHash);
      });
    });
  }
});
